#!/bin/bash
# Updates build_info.dart with current timestamp, then builds
# Usage: ./tool/build.sh [apk|windows] (default: apk)
set -e

TARGET="${1:-apk}"
shift 2>/dev/null || true

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S")
VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')

cat > lib/build_info.dart << EOF
// Generated by build script. Do not edit manually.
const String buildTimestamp = '$TIMESTAMP';
const String appVersion = '$VERSION';
EOF

echo "Build info: v$VERSION @ $TIMESTAMP"

case "$TARGET" in
  apk)
    flutter build apk --release "$@"
    ;;
  windows)
    flutter build windows --release "$@"
    ;;
  *)
    echo "Unknown target: $TARGET (use 'apk' or 'windows')"
    exit 1
    ;;
esac
